default: &default
  adapter: postgresql
  encoding: unicode
  host:     postgres
  database: Chat_te<%= Rails.env %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>

  pool: 5

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default